### ISSUE TITLE
Add Uni Freiburg

### ISSUE THREAD

**Issue by Nailuj1** [V3lop5/ilias-downloader#3]
Hi,
first of all, thx for making the tool! 

would it be possible to get the Uni Freiburg working?

here are the requested URL's:

```
URL nach eingeabe der Ilias Seite "ilias.uni-freiburg.de":	https://ilias.uni-freiburg.de/ilias.php?baseClass=ilrepositorygui&reloadpublic=1&cmd=frameset&ref_id=1
URL nach Login: 	https://ilias.uni-freiburg.de/goto.php?target=root_1
URL Kurs "Geomatik I - SS 2021":	https://ilias.uni-freiburg.de/ilias.php?ref_id=2124457&cmdClass=ilrepositorygui&cmdNode=zf&baseClass=ilrepositorygui
URL nach Logout:	https://ilias.uni-freiburg.de/ilias.php?lang=de&client_id=unifreiburg&cmd=showLogout&cmdClass=ilstartupgui&cmdNode=12q&baseClass=ilStartUpGUI
```

THX a lot

**Comment by V3lop5** [comment]
Hi @Nailuj1,

Unfortunately, your university uses a user-defined login system called "myLogin", not the default one provided by ilias. 
For now this script can't handle this. 🙁

I took a short look into it, I guess it would be possible to implement. You might create a fork of this repo.
