### ISSUE TITLE
Download von Dateien in exercise scheitert

### ISSUE THREAD

**Issue by emhl** [V3lop5/ilias-downloader#7]
Im log wird zwar angezeigt, dass ein Fetch durchgeführt wird, aber es werden keine der Dateien aus dem Übungsblätter "Ordner" heruntergeladen.

das problem tritt bei Ilias 6 auf
linkstruktur für eine Exercise `https://ilias.uni-konstanz.de/ilias.php?ref_id=xxxxxxx&target=xxxxxxx&cmd=showOverview&cmdClass=ilobjexercisegui&cmdNode=ba:mt&baseClass=ilexercisehandlergui`

Struktur Downloadlink für Datei in Exercise: `https://ilias.uni-konstanz.de/ilias.php?ref_id=xxxxxxx&file=blatt1.pdf&ass_id=XXXXX&cmd=downloadFile&cmdClass=ilexsubmissiongui&cmdNode=ba:mt:bq&baseClass=ilexercisehandlergui`

Struktur Downloadlink für eine submisson: `https://ilias.uni-konstanz.de/ilias.php?ref_id=xxxxxxx&ass_id=XXXXX&_table_nav=filetitle:asc:0&delivered=yyyyyy&cmd=download&cmdClass=ilexsubmissionfilegui&cmdNode=ba:mt:bq:bp&baseClass=ilexercisehandlergui`

**Comment by emhl** [comment]
btw. "Download von Übungsaufgaben" ist sowohl unter features als auch unter Roadmap gelistet. sollte das ganze normalerweise funktionieren oder noch nicht? :see_no_evil:

**Comment by V3lop5** [comment]
Hi @emhl,

danke für die Info! 

Das Vorgehen im Script ist wie folgt: 
1. Aufrufen der Übungsseite
2. Auffinden aller `Download` Buttons
3. Herunterladen der Dokumente, die sich hinter den `Download` Buttons verbergen

Durch die neue Ilias Version scheint sich der Link von den Übungsseiten geändert zu haben. Deshalb findet das Script die Übung nicht mehr. (Ich habe dieses Semester keine Abgabeübungen mehr, deshalb ist mir der Fehler nicht aufgefallen..)

Funktioniert bei der Uni Konstanz der Link `https://ilias.uni-konstanz.de/goto_ILIASKONSTANZ_exc_xxxxxxx.html`, um auf die Übersichtsseite der Übung zu gelangen?
(`xxxxxxx` ist der Wert aus `ref_id=xxxxxxx`)

Die Übersichtsseite sollte so aussehen:
![image](https://user-images.githubusercontent.com/44635962/140525436-9518807e-b5d8-49d7-9c00-8ac69c7bd6c0.png)

**Comment by emhl** [comment]
Ja, der Link funktioniert, allerdings wird man sofort automatisch zu ` https://ilias.uni-konstanz.de/ilias.php?ref_id=xxxxxxx&target=xxxxxxx&cmd=showOverview&cmdClass=ilobjexercisegui&cmdNode=ba:mt&baseClass=ilexercisehandlergui` weitergeleitet.

**Comment by V3lop5** [comment]
Hi @emhl, 

ich habe eine neue Version veröffentlicht: https://github.com/V3lop5/ilias-downloader/releases/tag/v0.0.6
Du kannst dir dort die überarbeitete Version von `IliasDownload.sh` herunterladen und die bestehende Datei ersetzen.
Anschließend sollten die Übungsblätter heruntergeladen werden.

**Comment by emhl** [comment]
hab gerade das neue skript geladen und bei mich funktioniert das herunterladen der Übungsblätter immernoch nicht. nach dem fetching exc xxxxxxx ... bricht das ganze immer ab

ich habe aber den fehler gefunden. bei der konstanzer ilias ist der Linktext vom Downloadbutton nicht "Download" sondern "Herunterladen". wenn man beim grep [hier](https://github.com/V3lop5/ilias-downloader/blob/2537b6dee6399be1657282e5fb83254e04d3ebb4/IliasDownload.sh#L176) den Text ersetzt funktioniert alles XD

Das mit den Übungsbüchern vs Abgabeübungen macht natürlich sinn :D

**Comment by V3lop5** [comment]
@emhl got it!

[Release v0.0.7](https://github.com/V3lop5/ilias-downloader/releases/tag/v0.0.7) löst auch dieses Problem. Die Beschreibung des Downloadbuttons ist jetzt eine Config-Variable, die für Uni Konstanz auf "Herunterladen" gesetzt ist.

Viel Spaß mit dem Downloader, es freut mich, dass der genutzt wird! 🐲
